### ISSUE TITLE
Issue with EB attempting to create IAM Role

### ISSUE THREAD

**Issue by zach5410** [gxela/awsebcli#26]
I am creating a custom platform and once eb creates an environment it terminates the environment because it does not have the permissions to create roles.

My company is strict on who can and cannot create IAM roles, so gaining access to create roles will not be possible.

I did adjust my platform.yaml file to include the following:

```
option_settings:
  - namespace: aws:elasticbeanstalk:environment
    option_name: ServiceRole
    value: svc/elasticbeanstalk-service-role
```

Which should have given the role to use upon creation.  

Is there another way to pass through a role to the cli so it can use said role instead of it trying to create its own?
